### PR TITLE
Update to Rack v0.6 API

### PR DESCRIPTION
**Pull request by cschol**
Update plugin to Rack API v0.6 incl. updated Makefile (reference: [Repair Team](https://github.com/VCVRack/community/issues/269)).

### CODE REVIEW

**Comment by IohannRabeson** [comment]
With OSX I'm not able to build. <samplerate.h> is not found with the latest rack:

`utils/WavWriter.cpp:94:3: error: use of undeclared identifier 'src_float_to_short_array'
                src_float_to_short_array(m_buffer.data()->samples, buffer.data(), sampleCount);
                ^
1 error generated.`

**Comment by cschol** [comment]
Yes, that is now a module specific dependency. `libsamplerate` was replaced by `libspeexdsp` in Rack itself for `v0.6`. Andrew's recommendation was staticly linking `libsamplerate` into the plugin if the relevant functions cannot be replaced. There is unfortunately no drop-in replacement for the `libsamplerate` functions (`src_float_to_short_array`) in `libspeexdsp`.

**Comment by cschol** [comment]
Per this [post](https://github.com/jeremywen/JW-Modules/wiki/Dev-FAQ-for-VCV-Rack#how-do-i-statically-link-against-a-library), the `Makefile` needs another update to support static linking on all platforms. I updated the PR.

**EDIT:** This works on Windows, but fails to link on Linux. Looks like `libsamplerate` on Linux cannot be statically linked because it was not compiled with `-fPIC` flag. I can't test on the Mac platform, but the only way around that in Linux would be to distribute `libsamplerate` with the plugin, like Rack did in `v0.5`. Or replace the `libsamplerate` code in the plugin.

**Comment by cschol** [comment]
Andrew provided a way to deal with `libsamplerate` in the Fundamental plugin. I used the same approach to update your plugin and updated the PR. Also fixed the latest API changes.

There is one issue left to fix on Windows, where the dependency build fails. This is an issue in Fundamental also and will be updated as soon as a solution is available.

**Comment by IohannRabeson** [comment]
I tried (quickly) to build it but without success on OSX. I will try again this week and I get back to you.

**Comment by fractalgee** [comment]
Yup, here is my Mac OS X build log, ClockDivider fails to compile with 4 errors also some warnings about usage of deprecated declarations. One of my fave plugins for sure, super handy, hope you can get these fixed soon.

[Build_Log_060.txt](https://github.com/IohannRabeson/VCVRack-Simple/files/1887254/Build_Log_060.txt)

**Comment by IohannRabeson** [comment]
@cschol I merged your changes but I removed the recorder. Thank you!

**Pull request merged**
